
// 词法定义
<数字> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" // 数字

<整数> ::= <数字>{<数字>} // 整数

<加号> ::= "+"
<减号> ::= "-"
<星号> ::= "*"
<除号> ::= "/"
<左小括号> ::= "("
<右小括号> ::= ")"


<小写字母> ::= "a" | "b" | "c" | "d" | "e" | "f" | "g"
        | "h" | "i" | "j" | "k" | "l" | "m" | "n"
        | "o" | "p" | "q" | "r" | "s" | "t"
        | "u" | "v" | "w"
        | "x" | "y" | "z"

<大写字母> ::= "A" | "B" | "C" | "D" | "E" | "F" | "G"
        | "H" | "I" | "J" | "K" | "L" | "M" | "N"
        | "O" | "P" | "Q" | "R" | "S" | "T"
        | "U" | "V" | "W"
        | "X" | "Y" | "Z"

<字母> ::= <小写字母> | <大写字母>


<下划线> ::= "_"

<非数字> ::= <字母> | <下划线>


<标识符> ::= <非数字>{<非数字>|<数字>}

<等号> ::= "="


<print> ::= "print"

<逗号> ::= ","

// 语法定义



// 表达式

// 参数列表
<参数列表> ::= <加减类表达式>{<逗号><加减类表达式>}
//
//<函数调用表达式> ::= <标识符><左小括号><参数列表><右小括号>

// 初值表达式
<初值表达式> ::= <整数>
                | <标识符>
//                | <函数调用表达式>
                |<左小括号><加减类表达式><右小括号>

// 一元表达式
<一元表达式> ::= <初值表达式>

// 乘除类表达式
<乘除类表达式> ::= <一元表达式>{
                            <星号><一元表达式>
                            | <除号><一元表达式>
                            }

// 加减类表达式
<加减类表达式> ::= <乘除类表达式> {
                                <加号><乘除类表达式>
                                | <减号><乘除类表达式>
                                }

// 赋值表达式
<赋值表达式> ::= <标识符><等号><加减类表达式>



// 表达式
<表达式> ::= <赋值表达式>
//            | <函数调用表达式>


// 语句

// print语句
<print语句> ::= <print><左小括号><参数列表><右小括号>

// 语句
<语句> ::= <表达式>
           |<print语句>


// 文件

<文件> ::= {<语句>}